---
controller_execution_environments:
  - name: leapp-snapshot-ee
    description: Execution environment for RHEL Leapp snapshot and upgrade automation
    image: "{{ snapshot_execution_environment | default('quay.io/philip860/leapp-upgrade:v3', true) }}"
    pull: always